language: php
notifications:
 email:
  - sdksupport@vantiv.com
env:
 global:
  - BUILD_DIR=`pwd`
  - CHARGEBACK_CONFIG_DIR=$BUILD_DIR/cnp/sdk
  - CHARGEBACK_CONFIG_FILE=$CHARGEBACK_CONFIG_DIR/chargeback_SDK_config.ini
install:
 - composer install
script:
 - echo $BUILD_DIR
 - echo $CHARGEBACK_CONFIG_FILE
 - echo 'username=USERNAME'>$CHARGEBACK_CONFIG_FILE
 - echo 'password=PASSWORD'>>$CHARGEBACK_CONFIG_FILE
 - echo "currency_merchant_map ['DEFAULT']=1288791">>$CHARGEBACK_CONFIG_FILE
 - echo 'url=https://www.testvantivcnp.com/sandbox'>>$CHARGEBACK_CONFIG_FILE
 - echo 'proxy='>>$CHARGEBACK_CONFIG_FILE
 - echo 'timeout=50000'>>$CHARGEBACK_CONFIG_FILE
 - echo 'printXml=true'>>$CHARGEBACK_CONFIG_FILE
 - echo 'neuterXml=0'>>$CHARGEBACK_CONFIG_FILE
 - cat $CHARGEBACK_CONFIG_FILE
 - phpunit --log-junit $BUILD_DIR/reports/tests.xml --coverage-clover=coverage.xml
after_success:
 - bash <(curl -s https://codecov.io/bash)
